import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import Cropper, { type Area } from 'react-easy-crop';
import { ImagePlus, LoaderCircle, Send } from 'lucide-react';
import { Dialog } from './Dialog';
import { prepareOriginal, cropDisplay } from '../lib/images';
import { api } from '../lib/api';
import type { Photo, Crop } from '../lib/types';
export function UploadDialog({ photo, onClose, onDone }: { photo?: Photo; onClose: () => void; onDone: () => void }) {
  const [blob, setBlob] = useState<Blob | null>(null), [url, setUrl] = useState(''), [position, setPosition] = useState({ x: 0, y: 0 }), [zoom, setZoom] = useState(1), [area, setArea] = useState<Crop | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''); const [preview, setPreview] = useState(''); const input = useRef<HTMLInputElement>(null);
  useEffect(() => { if (!blob) return; const object = URL.createObjectURL(blob); setUrl(object); return () => URL.revokeObjectURL(object) }, [blob]);
  useEffect(() => { if (!photo) return; let active = true; setBusy(true); fetch(photo.original_url).then(r => { if (!r.ok) throw Error('写真を取得できません。画面を更新して再試行してください。'); return r.blob() }).then(b => { if (active) setBlob(b) }).catch(e => { if (active) setError(e.message) }).finally(() => { if (active) setBusy(false) }); return () => { active = false } }, [photo]);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview) }, [preview]);
  async function choose(file?: File) { if (!file) return; setBusy(true); setError(''); setPreview(''); try { await new Promise(r => setTimeout(r, 40)); setBlob(await prepareOriginal(file)); setPosition({ x: 0, y: 0 }); setZoom(1); setArea(null) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  async function submit() { if (!blob || !area) return; setBusy(true); setError(''); try { await new Promise(r => setTimeout(r, 40)); const display = await cropDisplay(blob, area); if (photo) await api.recrop(photo.image_id, display, area); else await api.upload({ original: blob, display, crop: area }); onDone() } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  async function showPreview() { if (!blob || !area) return; try { setPreview(URL.createObjectURL(await cropDisplay(blob, area))) } catch (e) { setError((e as Error).message) } }
  const completeCrop = useCallback((_: Area, p: Area) => { setArea(previous => previous && previous.x === p.x && previous.y === p.y && previous.w === p.width && previous.h === p.height ? previous : { x: p.x, y: p.y, w: p.width, h: p.height }) }, []);
  useEffect(() => { setPreview('') }, [area]);
  const initial = useMemo(() => photo ? { x: photo.crop.x, y: photo.crop.y, width: photo.crop.w, height: photo.crop.h } : undefined, [photo]);
  return <Dialog title={photo ? '写真の切り取りを変更' : '家族に写真を届ける'} onClose={onClose} busy={busy}><p className="muted">親のフレームに映る範囲を、4:3の枠で選びます。</p><input ref={input} className="visually-hidden" type="file" accept="image/*" aria-label="写真を選択" onChange={e => void choose(e.target.files?.[0])} />{!url ? <button className="upload-drop" onClick={() => input.current?.click()} disabled={busy}><ImagePlus size={42} /><strong>写真を選ぶ</strong><span>JPEG・PNGなど／30MBまで</span></button> : <><div className="crop-container"><Cropper image={url} crop={position} zoom={zoom} aspect={4 / 3} onCropChange={setPosition} onZoomChange={setZoom} initialCroppedAreaPixels={initial} onCropComplete={completeCrop} showGrid={false} /></div><label className="zoom-control">拡大 <input type="range" min="1" max="3" step="0.01" value={zoom} onChange={e => setZoom(Number(e.target.value))} aria-label="写真の拡大率" /></label><div className="button-row">{!photo && <button className="text-button" disabled={busy} onClick={() => input.current?.click()}>別の写真を選ぶ</button>}<button className="text-button" disabled={busy || !area} onClick={() => void showPreview()}>表示イメージ</button></div>{preview && <figure className="crop-preview"><img src={preview} alt="親のフレームでの表示イメージ" /><figcaption>320 × 240の表示イメージ</figcaption></figure>}</>}{error && <p className="error" role="alert">{error}</p>}{busy && <p className="processing" role="status"><LoaderCircle className="spin" size={18} />写真を処理しています…</p>}<button className="primary full" disabled={!blob || !area || busy} onClick={() => void submit()}><Send size={18} />{photo ? '切り取りを保存' : 'この写真を送る'}</button><p className="fine-print">写真は順番に、設定した時刻に1日1枚届きます。</p></Dialog>
}
