import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { registerSW } from 'virtual:pwa-register';
import { Heart, House, Settings as SettingsIcon, Plus, ArrowUpRight, Clock3, Wifi, WifiOff, Bell, Check, ChevronRight, RefreshCw, Image as ImageIcon, Sun, FlaskConical, AlertTriangle, Upload } from 'lucide-react';
import { api, configured, isDemo, recropAvailable } from './lib/api';
import { getActivity, relativeTime, reorderPhotos } from './lib/status';
import { isIOS, standalone, subscribePush } from './lib/push';
import { setDemoScenario } from './lib/demo';
import type { ImageList, Photo } from './lib/types';
import { Queue } from './components/Queue';
import { UploadDialog } from './components/UploadDialog';
import { Dialog } from './components/Dialog';
const date = (v: string | null) => v ? new Date(v).toLocaleDateString('ja-JP', { month: 'long', day: 'numeric', timeZone: 'Asia/Tokyo' }) : '表示日時未取得';
export default function App() {
  const client = useQueryClient(); const [page, setPage] = useState<'home' | 'settings'>('home'); const [upload, setUpload] = useState(false); const [edit, setEdit] = useState<Photo | null>(null); const [deleting, setDeleting] = useState<Photo | null>(null); const [view, setView] = useState<Photo | null>(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [online, setOnline] = useState(navigator.onLine); const [now, setNow] = useState(Date.now()); const [installDismissed, setInstallDismissed] = useState(false); const [pushBusy, setPushBusy] = useState(false); const [subscribed, setSubscribed] = useState(false); const [updateWorker, setUpdateWorker] = useState<null | (() => void)>(null);
  const images = useQuery({ queryKey: ['images'], queryFn: api.images, enabled: configured, refetchInterval: 5 * 60000 });
  const status = useQuery({ queryKey: ['status'], queryFn: api.status, enabled: configured, refetchInterval: 30000 });
  const settings = useQuery({ queryKey: ['settings'], queryFn: api.settings, enabled: configured });
  const invalidate = () => { void client.invalidateQueries({ queryKey: ['images'] }); void client.invalidateQueries({ queryKey: ['status'] }); void client.invalidateQueries({ queryKey: ['settings'] }) };
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 15000); const network = () => { setOnline(navigator.onLine); if (navigator.onLine) invalidate() }; const update = (e: MessageEvent) => { if (e.data?.type === 'SERVER_UPDATE') invalidate() }; window.addEventListener('online', network); window.addEventListener('offline', network); navigator.serviceWorker?.addEventListener('message', update); return () => { clearInterval(timer); window.removeEventListener('online', network); window.removeEventListener('offline', network); navigator.serviceWorker?.removeEventListener('message', update) } }, [client]);
  useEffect(() => { if (!('serviceWorker' in navigator) || !import.meta.env.PROD) return; const update = registerSW({ onNeedRefresh() { setUpdateWorker(() => () => { void update(true) }) }, onRegisterError() { setError('通知機能を準備できませんでした。再読み込みしてください。') } }) }, []);
  useEffect(() => { if (!message) return; const timer = setTimeout(() => setMessage(''), 6000); return () => clearTimeout(timer) }, [message]);
  const report = (e: Error) => setError(e.message);
  const changeSettings = useMutation({ mutationFn: api.updateSettings, onSuccess: (data) => { client.setQueryData(['settings'], data); void client.invalidateQueries({ queryKey: ['status'] }); setMessage('設定を保存しました') }, onError: report });
  const advance = useMutation({ mutationFn: api.advance, onSuccess: () => { invalidate(); setMessage(isDemo ? 'デモの表示写真を切り替えました' : '写真の切替を実行しました') }, onError: report });
  const remove = useMutation({ mutationFn: api.remove, onSuccess: () => { setDeleting(null); invalidate(); setMessage('写真を削除しました') }, onError: report });
  const reorder = useMutation({ mutationFn: ({ id, after }: { id: string; after: string | null }) => api.reorder(id, after), onMutate: async ({ id, after }) => { await client.cancelQueries({ queryKey: ['images'] }); const previous = client.getQueryData<ImageList>(['images']); if (previous) { const queue = reorderPhotos(previous.images.filter(p => p.status === 'queued').sort((a, b) => a.sort_order - b.sort_order), id, after).map((p, i) => ({ ...p, sort_order: i })); client.setQueryData(['images'], { ...previous, images: [...previous.images.filter(p => p.status !== 'queued'), ...queue] }) } return { previous } }, onError: (e, _, context) => { if (context?.previous) client.setQueryData(['images'], context.previous); report(e) }, onSettled: () => client.invalidateQueries({ queryKey: ['images'] }) });
  const list = images.data; const current = list?.images.find(p => p.image_id === list.current_image_id); const queued = (list?.images ?? []).filter(p => p.status === 'queued').sort((a, b) => a.sort_order - b.sort_order); const history = (list?.images ?? []).filter(p => p.status === 'displayed' && p.image_id !== list?.current_image_id).sort((a, b) => Date.parse(b.displayed_at ?? '') - Date.parse(a.displayed_at ?? ''));
  const activity = getActivity(status.data ?? null, list?.last_detected_at ?? null, now); const stale = !online || images.isError || status.isError; const testMode = settings.data?.test_mode ?? status.data?.test_mode; const loading = images.isPending && configured; const disabled = !online || !configured;
  async function enablePush() { setPushBusy(true); setError(''); try { await subscribePush(); setSubscribed(true); setMessage('通知の受信を登録しました') } catch (e) { report(e as Error) } finally { setPushBusy(false) } }
  function showSettings() { setPage('settings'); window.scrollTo({ top: 0 }) }
  const notice = <section className="notification-card"><span className="round-icon"><Bell size={22} /></span><div><h3>大切な反応を、見逃さないために</h3><p>{subscribed ? 'この端末の通知を登録しました。' : '反応がないときや、いいねが届いたときにお知らせ。'}</p></div><button className="text-button" disabled={pushBusy || subscribed || disabled || isDemo} onClick={() => void enablePush()}>{pushBusy ? '登録中…' : subscribed ? '登録済み' : '通知を設定'}<ChevronRight size={16} /></button></section>;
  return <div className="app-shell"><aside className="desktop-sidebar"><a className="brand" href="/" aria-label="見守り ホーム"><span className="brand-symbol"><House size={22} /><Heart size={10} /></span>見守り<span className="brand-dot">.</span></a><p className="tagline">離れていても、<br />今日がつながる。</p><nav aria-label="メインメニュー"><button className={page === 'home' ? 'selected' : ''} onClick={() => setPage('home')}><House size={20} />ホーム</button><button className={page === 'settings' ? 'selected' : ''} onClick={showSettings}><SettingsIcon size={20} />設定</button></nav><div className="sidebar-note"><Sun size={26} /><p>写真を一枚。<br />今日の気持ちを届けよう。</p></div><span className="sidebar-bottom">FAMILY, EVERY DAY.</span></aside><div className="main-wrap"><header className="topbar"><a className="brand mobile-brand" href="/"><span className="brand-symbol"><House size={22} /><Heart size={10} /></span>見守り<span className="brand-dot">.</span></a><span className="desktop-greeting">家族の毎日を、そっと。</span><div className="top-actions"><button className={`test-toggle ${testMode ? 'active' : ''}`} role="switch" aria-checked={!!testMode} aria-label="テストモード" disabled={changeSettings.isPending || disabled || testMode === undefined} onClick={() => changeSettings.mutate({ test_mode: !testMode })}><FlaskConical size={15} /><span>テスト</span><span className="switch-track"><span /></span></button><button className="icon-button" aria-label="設定を開く" onClick={showSettings}><SettingsIcon size={20} /></button></div></header>
    {isDemo && <div className="demo-banner"><FlaskConical size={15} /><span>画面デモ · 実機・サーバー未接続</span><select aria-label="デモの状態" defaultValue="normal" onChange={e => { setDemoScenario(e.target.value); invalidate() }}><option value="normal">反応あり</option><option value="warning">反応なし</option><option value="offline">通信断</option><option value="empty">写真なし</option></select></div>}
    {testMode && <div className="test-banner"><FlaskConical size={18} /><span>テストモード中 · 通知間隔を短縮しています</span><button disabled={advance.isPending || disabled} onClick={() => advance.mutate()}>{advance.isPending ? '切替中…' : '切替を今すぐ実行'}</button></div>}
    {!configured && <div className="error connection-notice" role="status">接続準備中です。APIのURLと端末IDが設定されると、ご家族の情報を取得します。</div>}
    {stale && <div className="error connection-notice" role="alert"><WifiOff size={18} /><span>最新情報を取得できません。{images.dataUpdatedAt ? `表示は${new Date(images.dataUpdatedAt).toLocaleTimeString('ja-JP')}時点です。` : ''}</span><button className="text-button" onClick={invalidate}>再試行</button></div>}
    {error && <div className="error connection-notice" role="alert">{error}<button className="text-button" onClick={() => setError('')}>閉じる</button></div>}
    {updateWorker && <div className="notification-card"><p>新しいバージョンがあります。写真の編集中は、保存してから更新してください。</p><button onClick={updateWorker} className="text-button" disabled={upload || !!edit}>更新する</button></div>}
    {isIOS() && !standalone() && !installDismissed && <section className="install-card"><Upload size={24} /><div><strong>通知を受け取る準備をしましょう</strong><p>Safariの共有ボタン →「ホーム画面に追加」。追加したアイコンから開いて、通知を許可してください。</p></div><button className="text-button" onClick={() => setInstallDismissed(true)}>あとで</button></section>}
    <main>{page === 'home' ? <><div className="page-heading"><div><span className="eyebrow">YOUR FAMILY</span><h1>今日の見守り</h1><p>いつもの毎日に、家族のつながりを。</p></div><span className="today">{new Date(now).toLocaleDateString('ja-JP', { month: 'long', day: 'numeric', weekday: 'short' })}</span></div>
      <section className={`status-card ${stale ? 'unknown' : activity.tone}`} aria-label="見守りの状態"><div className="status-top"><span className="status-label"><span className="status-dot" />{stale ? '情報の更新を確認できません' : loading ? '反応を確認しています' : activity.title}</span><button className="icon-button" aria-label="状態を更新" onClick={invalidate} disabled={!configured || images.isFetching}><RefreshCw size={17} className={images.isFetching ? 'spin' : ''} /></button></div><div className="status-main"><span className="status-orbit">{stale ? <WifiOff size={29} /> : activity.tone === 'normal' ? <Check size={32} /> : activity.tone === 'alert' || activity.tone === 'warning' ? <AlertTriangle size={29} /> : <Clock3 size={29} />}</span><div><p className="status-caption">最後に動きを検知</p><strong>{loading ? '確認中…' : relativeTime(status.data?.last_detected_at ?? list?.last_detected_at ?? null, now)}</strong></div></div><div className="status-footer"><span><Wifi size={15} />機器の通信：{status.data?.last_seen_at ? relativeTime(status.data.last_seen_at, now) : '未取得'}</span><span>{list ? `${list.images.filter(p => p.status !== 'deleted').length}枚中 ${list.display_seq}枚表示済み` : '写真の記録を待っています'}</span></div><p className="status-explanation">{stale ? '接続が戻るまで、過去の記録としてご確認ください。' : activity.detail}</p></section>
      <div className="content-columns"><div className="photo-column"><section className="current-section"><div className="section-heading"><h2>いま、親のフレームに</h2><span className="subtle-label">TODAY'S PHOTO</span></div>{loading ? <div className="photo-skeleton skeleton" /> : current ? <article className="current-card"><button className="hero-photo" onClick={() => setView(current)} aria-label="表示中の写真を大きく見る"><img src={current.display_url} alt="親のフレームに表示する写真" /><span className="photo-badge"><span />表示中</span><span className="expand-icon"><ArrowUpRight size={21} /></span></button><div className="photo-caption"><div><span className="eyebrow">A LITTLE MOMENT</span><h3>{date(current.displayed_at)}からの一枚</h3></div>{current.liked_at ? <span className="like-badge"><Heart size={17} fill="currentColor" />いいねが届きました</span> : <span className="muted small">{current.liked_at === undefined ? 'いいね情報は未取得' : 'いいねの記録はまだありません'}</span>}</div></article> : <div className="empty-state"><ImageIcon size={38} /><h3>最初の一枚を届けませんか</h3><p>何気ない日常も、家族にはうれしい便りです。</p><button className="primary" disabled={disabled} onClick={() => setUpload(true)}><Plus size={18} />写真を追加</button></div>}</section>
        <section className="queue-section"><div className="section-heading"><h2>これから届く写真 <span className="count">{queued.length}</span></h2><span className="muted small">1日1枚ずつ</span></div>{queued.length > 0 ? <><p className="section-help">持ち手をドラッグ、または矢印で順番を変えられます。</p><Queue photos={queued} disabled={disabled || reorder.isPending || remove.isPending} onReorder={(id, after) => reorder.mutate({ id, after })} onEdit={setEdit} onDelete={setDeleting} canEdit={recropAvailable} /></> : <div className="queue-empty"><ImageIcon size={23} /><p>次の写真を追加しておきましょう。</p></div>}</section></div>
        <aside className="story-column"><section className="send-card"><span className="eyebrow">ONE PHOTO, ONE SMILE</span><div className="little-art"><div className="art-frame back" /><div className="art-frame front"><Sun size={24} /><div className="art-hill" /><Heart size={22} /></div><span className="art-spark">✳</span></div><h2>なんでもない今日が、<br />うれしい便りになる。</h2><p>おいしかったごはんも、<br />散歩で見つけた景色も。</p><button className="primary full" disabled={disabled} onClick={() => setUpload(true)}><Plus size={20} />写真を追加する</button><span className="small muted">次の切替 {settings.data ? `${settings.data.switch_time.slice(0, 5)}（日本時間）` : '時刻を取得していません'}</span></section>{notice}<section className="history-section"><div className="section-heading"><h2>これまでの写真</h2><span className="count">{history.length}</span></div>{history.length ? <div className="history-grid">{history.map(p => <button className="history-photo" key={p.image_id} onClick={() => setView(p)}><img src={p.original_url} alt={`${date(p.displayed_at)}に表示した写真`} loading="lazy" /><span>{date(p.displayed_at)}{p.liked_at && <Heart size={13} fill="currentColor" />}</span></button>)}</div> : <p className="muted small">表示された写真が、ここに残ります。</p>}</section></aside></div><p className="footer-note">動きの記録は、健康状態や本人の無事を保証するものではありません。</p></> : <><div className="page-heading"><div><span className="eyebrow">PREFERENCES</span><h1>見守りの設定</h1><p>ご家族の暮らしに合わせて。</p></div></div><section className="settings-card"><div className="setting-title"><Clock3 size={24} /><div><h2>写真の切替時刻</h2><p>毎日この時刻に、次の一枚へ切り替わります。</p></div></div>{!settings.data && <p className="muted">現在の設定は未取得です。下の時刻を保存すると設定できます。</p>}<form onSubmit={e => { e.preventDefault(); changeSettings.mutate({ switch_time: String(new FormData(e.currentTarget).get('switch_time')) }) }}><label htmlFor="switch-time">日本時間（JST）</label><div className="time-row"><input id="switch-time" name="switch_time" type="time" required key={settings.data?.switch_time ?? 'unconfigured'} defaultValue={settings.data?.switch_time.slice(0, 5) ?? '00:00'} /><button className="primary" disabled={disabled || changeSettings.isPending}>保存する</button></div></form><p className="fine-print">次の写真がない日は、前の写真をそのまま表示します。</p></section>{notice}<section className="settings-card"><div className="setting-title"><FlaskConical size={24} /><div><h2>テストモード</h2><p>動作確認用に、検知通知と機器の更新間隔を短くします。</p></div></div><p className="fine-print">現在：{testMode === undefined ? '未取得' : testMode ? 'オン' : 'オフ'}。確認後はオフに戻してください。</p><div className="button-row"><button className="secondary" disabled={disabled || changeSettings.isPending} onClick={() => changeSettings.mutate({ test_mode: !testMode })}>{testMode ? 'テストを終了する' : 'テストを開始する'}</button>{testMode && <button className="secondary" disabled={disabled || advance.isPending} onClick={() => advance.mutate()}>切替を今すぐ実行</button>}</div></section><p className="fine-print">{isDemo ? '画面デモの変更は再読み込みでリセットされます。' : 'このMVPは固定の親1台・子1人の構成です。'}</p></>}</main>
    <nav className="mobile-nav" aria-label="下部メニュー"><button className={page === 'home' ? 'selected' : ''} onClick={() => { setPage('home'); window.scrollTo({ top: 0 }) }}><House size={21} />ホーム</button><button className="nav-add" disabled={disabled} onClick={() => setUpload(true)}><span><Plus size={22} /></span>写真を追加</button><button className={page === 'settings' ? 'selected' : ''} onClick={showSettings}><SettingsIcon size={21} />設定</button></nav></div>
    {message && <div className="toast" role="status"><Check size={18} />{message}</div>}
    {(upload || edit) && <UploadDialog photo={edit ?? undefined} onClose={() => { setUpload(false); setEdit(null) }} onDone={() => { setUpload(false); setEdit(null); invalidate(); setMessage(isDemo ? 'デモに写真を保存しました' : '写真を保存しました') }} />}
    {deleting && <Dialog title="この写真を削除しますか？" onClose={() => setDeleting(null)} busy={remove.isPending}><img className="delete-preview" src={deleting.display_url} alt="削除する写真" /><p>これから届く写真から取り除きます。この操作は取り消せません。</p><div className="button-row"><button className="secondary" disabled={remove.isPending} onClick={() => setDeleting(null)}>キャンセル</button><button className="danger" disabled={remove.isPending} onClick={() => remove.mutate(deleting.image_id)}>削除する</button></div>{remove.isError && <p role="alert" className="error">{remove.error.message}</p>}</Dialog>}
    {view && <Dialog title="家族に届いた写真" onClose={() => setView(null)}><img className="full-photo" src={view.original_url} alt="送信した写真の全体" /><p className="muted">{date(view.displayed_at)}{view.liked_at ? ' · いいねが届きました' : ''}</p></Dialog>}
  </div>
}
